/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.MenuManager;
import java.awt.Color;
import java.awt.event.ActionListener;
import model.User;

/**
 *
 * @author Lenovo
 */
public class FRM_Menu extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Menu
     */
    public FRM_Menu() {
        initComponents();
        esconderMenu();
    }

    public void escucharMenu(ActionListener manejador) {
        this.btReportes.addActionListener(manejador);
        this.btReservaciones.addActionListener(manejador);
        this.btCerrarSesion.addActionListener(manejador);
    }

    public void escucharBotonesUser(ActionListener manejador) {
        this.btIniciarSesion.addActionListener(manejador);
        this.btReportes.addActionListener(manejador);
        this.btReservaciones.addActionListener(manejador);
    }

    public void setUsuario(User user) {
        jtUsuario.setText(user.getUsername());
        jtContraseña.setText(user.getPassword());
    }
    
    public User getUsuario() {
        return new User(jtUsuario.getText(), jtContraseña.getText());
    }

    public void limpiar() {
        jtUsuario.setText("");
        jtContraseña.setText("");
    }

    public void esconderMenu() {
        btReportes.setVisible(false);
        btReservaciones.setVisible(false);
        btCerrarSesion.setVisible(false);
        jlTitulo.setText("Inicio de sesion parqueo Juarez");
    }

    public void mostrarMenu() {
        btReportes.setVisible(true);
        btReservaciones.setVisible(true);
        btCerrarSesion.setVisible(true);
        jlTitulo.setText("Menu principal parqueo Juarez");
        jPanel2.setBackground(new java.awt.Color(73, 104, 136));
    }

    public void mostrarLogin() {
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jtUsuario.setVisible(true);
        jtContraseña.setVisible(true);
        btIniciarSesion.setVisible(true);
        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
    }

    public void esconderLogin() {
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jtUsuario.setVisible(false);
        jtContraseña.setVisible(false);
        btIniciarSesion.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtUsuario = new javax.swing.JTextField();
        jlTitulo = new javax.swing.JLabel();
        btIniciarSesion = new javax.swing.JButton();
        btCerrarSesion = new javax.swing.JButton();
        btReportes = new javax.swing.JButton();
        btReservaciones = new javax.swing.JButton();
        jtContraseña = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lemon", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 110, 50));

        jLabel2.setFont(new java.awt.Font("Lemon", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 130, 50));

        jtUsuario.setFont(new java.awt.Font("Doppio One", 0, 18)); // NOI18N
        jPanel2.add(jtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 180, -1));

        jlTitulo.setFont(new java.awt.Font("Castellar", 3, 24)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jlTitulo.setText("Inicio de sesion Parqueo Juarez");
        jPanel2.add(jlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 520, 47));

        btIniciarSesion.setFont(new java.awt.Font("Ubuntu Mono", 3, 18)); // NOI18N
        btIniciarSesion.setText("Iniciar sesion");
        btIniciarSesion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 255)));
        jPanel2.add(btIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 150, 40));

        btCerrarSesion.setBackground(new java.awt.Color(0, 0, 0));
        btCerrarSesion.setFont(new java.awt.Font("Ubuntu Mono", 3, 24)); // NOI18N
        btCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btCerrarSesion.setText("Cerrar sesion");
        btCerrarSesion.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(102, 0, 0)));
        btCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(btCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 190, 50));

        btReportes.setBackground(new java.awt.Color(0, 0, 0));
        btReportes.setFont(new java.awt.Font("Ubuntu Mono", 3, 24)); // NOI18N
        btReportes.setForeground(new java.awt.Color(255, 255, 255));
        btReportes.setText("Reportes");
        btReportes.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 255, 255)));
        btReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReportesActionPerformed(evt);
            }
        });
        jPanel2.add(btReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 190, 50));

        btReservaciones.setBackground(new java.awt.Color(0, 0, 0));
        btReservaciones.setFont(new java.awt.Font("Ubuntu Mono", 3, 24)); // NOI18N
        btReservaciones.setForeground(new java.awt.Color(255, 255, 255));
        btReservaciones.setText("Reservaciones");
        btReservaciones.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 255, 51)));
        btReservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReservacionesActionPerformed(evt);
            }
        });
        jPanel2.add(btReservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 190, 50));

        jtContraseña.setFont(new java.awt.Font("Doppio One", 0, 18)); // NOI18N
        jtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtContraseñaActionPerformed(evt);
            }
        });
        jPanel2.add(jtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 180, -1));

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btReportesActionPerformed

    private void btReservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReservacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btReservacionesActionPerformed

    private void jtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtContraseñaActionPerformed



    public void addLoginListener(MenuManager.LoginListener loginListener) {
        btIniciarSesion.addActionListener(loginListener);
    }

    public void addLogoutListener(MenuManager.LogoutListener logoutListener) {
        btCerrarSesion.addActionListener(logoutListener);
    }
    
    public void addReportesListener(MenuManager.ReportsListener reportesListener) {
        btReportes.addActionListener(reportesListener);
    }

    public void addReservacionesListener(MenuManager.ReservationsListener reservacionesListener) {
        btReservaciones.addActionListener(reservacionesListener);
    }

    public String getUsername() {
        return jtUsuario.getText();
    }

    public String getPassword() {
        return jtContraseña.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCerrarSesion;
    private javax.swing.JButton btIniciarSesion;
    private javax.swing.JButton btReportes;
    private javax.swing.JButton btReservaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JPasswordField jtContraseña;
    private javax.swing.JTextField jtUsuario;
    // End of variables declaration//GEN-END:variables
}
