/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.MenuManager;
import java.awt.event.ActionListener;
import model.User;

/**
 *
 * @author Lenovo
 */
public class FRM_Menu extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Menu
     */
    public FRM_Menu() {
        initComponents();
        esconderMenu();
    }

    public void escucharMenu(ActionListener manejador) {
        this.jmiCliente.addActionListener(manejador);
        this.jmiReporte.addActionListener(manejador);
        this.jmiReservaciones.addActionListener(manejador);
        this.jmiSalir.addActionListener(manejador);
    }

    public void escucharBotonesUser(ActionListener manejador) {
        this.btIniciarSesion.addActionListener(manejador);
        this.btCerrarSesion.addActionListener(manejador);
    }

    public void setUsuario(User user) {
        jtUsuario.setText(user.getUsername());
        jtContraseña.setText(user.getPassword());
    }
    
    public User getUsuario() {
        return new User(jtUsuario.getText(), jtContraseña.getText());
    }

    public void limpiar() {
        jtUsuario.setText("");
        jtContraseña.setText("");
    }

    public void esconderMenu() {
        jmiCliente.setVisible(false);
        jmiReporte.setVisible(false);
        jmiReservaciones.setVisible(false);
        jmiSalir.setVisible(false);
    }

    public void mostrarMenu() {
        jmiCliente.setVisible(true);
        jmiReporte.setVisible(true);
        jmiReservaciones.setVisible(true);
        jmiSalir.setVisible(true);
    }

    public void mostrarLogin() {
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jtUsuario.setVisible(true);
        jtContraseña.setVisible(true);
        btIniciarSesion.setVisible(true);
        btCerrarSesion.setVisible(true);
    }

    public void esconderLogin() {
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jtUsuario.setVisible(false);
        jtContraseña.setVisible(false);
        btIniciarSesion.setVisible(false);
        btCerrarSesion.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtContraseña = new javax.swing.JTextField();
        jtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btIniciarSesion = new javax.swing.JButton();
        btCerrarSesion = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmiReservaciones = new javax.swing.JMenu();
        jmiCliente = new javax.swing.JMenuItem();
        jmiReporte = new javax.swing.JMenuItem();
        Reservaciones = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        jLabel3.setText("Usuario");

        btIniciarSesion.setText("Iniciar sesion");

        btCerrarSesion.setText("Cerrar sesion");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jtUsuario))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(186, 186, 186))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btIniciarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCerrarSesion)
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIniciarSesion)
                    .addComponent(btCerrarSesion))
                .addGap(50, 50, 50))
        );

        jmiReservaciones.setText("File");

        jmiCliente.setText("Reservar cliente");
        jmiReservaciones.add(jmiCliente);

        jmiReporte.setText("Reporte");
        jmiReservaciones.add(jmiReporte);

        Reservaciones.setText("Reservaciones");
        jmiReservaciones.add(Reservaciones);

        jMenuBar1.add(jmiReservaciones);

        jMenu2.setText("Edit");

        jmiSalir.setText("Salir");
        jMenu2.add(jmiSalir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    public void addLoginListener(MenuManager.LoginListener loginListener) {
        btIniciarSesion.addActionListener(loginListener);
    }

    public void addLogoutListener(MenuManager.LogoutListener logoutListener) {
        btCerrarSesion.addActionListener(logoutListener);
    }

    public String getUsername() {
        return jtUsuario.getText();
    }

    public String getPassword() {
        return jtContraseña.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Reservaciones;
    private javax.swing.JButton btCerrarSesion;
    private javax.swing.JButton btIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem jmiCliente;
    private javax.swing.JMenuItem jmiReporte;
    private javax.swing.JMenu jmiReservaciones;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JTextField jtContraseña;
    private javax.swing.JTextField jtUsuario;
    // End of variables declaration//GEN-END:variables
}
